version: "3.7"

services:
  log-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: log-service
    ports:
      - "3002:3002"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - resolute

networks:
  resolute:
    driver: bridge

volumes:
  data:
    driver: local
